name: brn_ecommerce
description: Loja Virtual pertencente a empresa - BRN Info_Dev (CNPJ. 52.129.576./001-57)-
  Desenvolvida pelo Analista e Dev. Bruno Salgado.
  Contato (82) 9 9984-5889
  Copyright 2024.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.6+01

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  alphabet_list_scroll_view_fix: ^2.0.2
  assets_audio_player: ^3.1.1
  auto_size_text: ^3.0.0
    # 1.14.3 depends of  intl ^0.19.0
  brasil_fields: ^1.14.1
  carousel_slider: ^4.2.1
  cloud_firestore: ^4.17.1
  collection: ^1.18.0
  credit_card_type_detector: ^3.0.0
  cupertino_icons: ^1.0.8
  custom_universal_html: ^2.0.0
  decorated_text: ^0.1.0
  dio: ^5.4.3+1
  fan_carousel_image_slider: ^0.1.2
  firebase_analytics: ^10.10.3
  firebase_auth: ^4.19.3
  firebase_core: ^2.30.1
  firebase_crashlytics: ^3.5.3
  firebase_performance: ^0.9.4+3
  firebase_remote_config: ^4.4.3
  firebase_storage: ^11.7.3
  flip_card: ^0.7.0
  flutter_colorpicker: ^1.0.3
    # 6.2.0 depends of HTTP 1.0
  flutter_facebook_auth: ^5.0.11
  flutter_markdown: ^0.7.1
  flutter_slidable: ^3.1.0
  flutter_spinkit: ^5.2.1
    # 2.0.10+1  depends of HTTP 1.0
  flutter_svg: ^2.0.9
  font_awesome_flutter: ^10.7.0
  gallery_saver: ^2.3.2
  geolocator: ^11.0.0
    # 6.2.1 depends of HTTP 1.0
  google_fonts: ^4.0.4
  google_sign_in: ^6.2.1
    # 1.2.1 depends of
  http: ^0.13.3
    # 5.0.1 depends of HTTP 1.2.1
  image_cropper: ^4.0.1
  image_picker: ^1.1.0
    # 0.19.0  depends of
  intl: ^0.18.1
  keyboard_actions: ^4.2.0
  mailer: ^6.1.0
  map_launcher: ^3.3.0
  markdown_editable_textinput: ^2.2.0
  package_info_plus: ^8.0.0
  path_provider: ^2.1.3
  permission_handler: ^11.3.1
  provider: ^6.1.2
  screenshot: ^2.3.0
  share_plus: ^9.0.0
  sliding_up_panel: ^2.0.0+1
  staggered_grid_view_flutter: ^0.0.4
  transparent_image: ^2.0.1
  url_launcher: ^6.2.6
  url_strategy: ^0.2.0
    # 4.4.0 depends of assets_audio_player ^3.1.1 no existe
  uuid: ^3.0.7
  youtube_player_iframe: ^4.0.4

      #  //TODO: Verificação de dependencias
  #  youtube_player_iframe_web: ^3.0.1   # depends on HTTP 1.2.1
  #  mobx: ^2.3.3+2
  #  flutter_mobx: ^2.2.1+1
       #  //TODO: configurar go_router
  #  go_router: ^7.1.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  analyzer: ^6.4.1
  build_runner: ^2.4.9
  build_web_compilers: ^4.0.10
  device_preview: ^1.1.0
  file: ^7.0.0
  flutter_lints: ^3.0.2
  lint: ^2.3.0
  logger: ^2.2.0
  mockito: ^5.4.4

  # //TODO: Verificação de dependencias
  #  intl_translation: ^0.18.2

# The following section is specific to Flutter packages.
flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/logo/
    - assets/docs/
    - assets/vignette/
    - assets/icons/
    - lib/
    - lib/common/
    - lib/common/cards/
    - lib/common/buttons/
    - lib/common/functions/
    - lib/common/drawer/
    - lib/common/drawer/components/
    - lib/models/
    - lib/models/locations_services/
    - lib/helpers/
    - lib/helpers/themes/
    - lib/helpers/themes/factory_colors/
    - lib/views/
    - lib/views/cart/
    - lib/views/cart/components/
    - lib/views/home/
    - lib/views/home/components/
    - lib/views/login/
    - lib/views/orders/
    - lib/views/orders/components/
    - lib/views/stores/
    - lib/views/stores/components/
    - lib/views/address/
    - lib/views/address/components/
    - lib/views/sign_up/
    - lib/views/checkout/
    - lib/views/checkout/components/
    - lib/views/products/
    - lib/views/products/components/
    - lib/views/who_we_are/
    - lib/views/who_we_are/components/
    - lib/views/admin_users/
    - lib/views/stores_edit/
    - lib/views/stores_edit/components/
    - lib/views/admin_orders/
    - lib/views/product_edit/
    - lib/views/product_edit/components/
    - lib/views/products_share/
    - lib/views/products_share/components/
    - lib/views/product_details/
    - lib/views/product_selected/
    - lib/views/sales_confirmation/
    - lib/views/policy_and_documents/
    - lib/views/policy_and_documents/components/
    - lib/services/
    - lib/services/db_api/
    - lib/generated/
    - lib/l10n/
    - lib/views/admin_settings/
    - lib/views/admin_settings/components/
    - lib/views/product_categories/
    - lib/views/product_categories/components/
    - lib/common/messengers/
    - lib/common/messengers/components/
    - lib/common/advertising/
    - lib/common/advertising/components/
    - lib/common/miscellaneous/
    - lib/common/formatted_fields/
    - lib/common/sliding_up_panel/
    - lib/common/sliding_up_panel/components/
    - lib/models/sales/
    - lib/models/users/
    - lib/models/views/
    - lib/models/products/
    - lib/models/products/categories/
    - lib/models/admin_area/
    - lib/models/admin_area/configs/
    - lib/models/users_area/
    - lib/helpers/product_categories_factory_lists/
    - lib/services/config/
    - lib/services/development_monitoring/
    - lib/services/firebase_remote_configs/
    - lib/generated/intl/
    - lib/generated/l10n/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages

flutter_intl:
  enabled: false
