name: brn_ecommerce
description: Loja Virtual BRN Info_Dev

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.3+01

environment:
  sdk: '>=3.0.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.18.1
  collection: ^1.17.2
  cupertino_icons: ^1.0.6
  cloud_firestore: ^4.9.3
  firebase_auth: ^4.10.1
  firebase_storage: ^11.2.8
  firebase_core: ^2.17.0
  firebase_performance: ^0.9.2+7
  firebase_remote_config: ^4.2.7
  firebase_analytics: ^10.5.1
  firebase_crashlytics: ^3.3.7
  provider: ^6.0.5
  fan_carousel_image_slider: ^0.1.2
  carousel_slider: ^4.2.1
  staggered_grid_view_flutter: ^0.0.4
  transparent_image: ^2.0.1
  alphabet_list_scroll_view_fix: ^2.0.2
  flutter_slidable: ^3.0.0
  url_launcher: ^6.1.14
  image_picker: ^1.0.4
  custom_universal_html: ^2.0.0
  image_cropper: ^4.0.1
  path_provider: ^2.1.1
  uuid: ^3.0.7
  dio: ^5.3.3
  brasil_fields: ^1.14.0
  geolocator: ^10.1.0
  sliding_up_panel: ^2.0.0+1
  screenshot: ^2.1.0
  http: ^0.13.3
  gallery_saver: ^2.3.2
  font_awesome_flutter: ^10.5.0
  permission_handler: ^11.0.1
  share_plus: ^7.1.0
  markdown_editable_textinput: ^2.2.0
  flutter_markdown: ^0.6.17+3
  youtube_player_iframe: ^4.0.4
  flutter_colorpicker: ^1.0.3
  flutter_spinkit: ^5.2.0
  flutter_facebook_auth: ^5.0.11
  google_sign_in: ^6.1.5
  package_info_plus: ^4.1.0
  assets_audio_player: ^3.1.1
  map_launcher: ^2.5.0+1
  flutter_svg: ^2.0.7
  url_strategy: ^0.2.0
  flip_card: ^0.7.0
  credit_card_type_detector: ^3.0.0
  keyboard_actions: ^4.2.0
  mailer: ^6.0.1
  auto_size_text: ^3.0.0
  google_fonts: ^4.0.4
  decorated_text: ^0.1.0
  flutter_screenutil: ^5.9.0
#  //TODO: configurar go_router
  #  go_router: ^7.1.1

#Para Testar um front end feito no FlutterFlow
#  cached_network_image: ^3.2.3
#  equatable: ^2.0.5
#  flutter_animate: ^4.2.0+1
#  flutter_cache_manager: ^3.3.1
#  from_css_color: ^2.0.0
#  json_path: ^0.6.2
#  mime_type: ^1.0.0
#  page_transition: ^2.0.4
#  path_provider_android: ^2.0.25
#  path_provider_foundation: ^2.2.2
#  path_provider_platform_interface: ^2.0.6
#  rxdart: ^0.27.7
#  timeago: ^3.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  lint: ^2.1.2
  analyzer: ^6.2.0
  logger: ^2.0.2+1
  flutter_lints: ^2.0.3
#  intl_translation: ^0.18.2
  file: ^7.0.0
  build_web_compilers: ^4.0.5
  build_runner: ^2.4.6
  device_preview: ^1.1.0

# The following section is specific to Flutter packages.
flutter:

  uses-material-design: true

  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  assets:
    - assets/images/
    - assets/logo/
    - assets/docs/
    - assets/vignette/
    - assets/icons/
    - lib/
    - lib/common/
    - lib/common/cards/
    - lib/common/button/
    - lib/common/functions/
    - lib/common/custom_drawer/
    - lib/common/custom_drawer/components/
    - lib/models/
    - lib/models/chearch_cep/
    - lib/helpers/
    - lib/helpers/themes/
    - lib/helpers/themes/factory_colors/
    - lib/screens/
    - lib/screens/base/
    - lib/screens/cart/
    - lib/screens/cart/components/
    - lib/screens/home/
    - lib/screens/home/components/
    - lib/screens/login/
    - lib/screens/orders/
    - lib/screens/orders/components/
    - lib/screens/stores/
    - lib/screens/stores/components/
    - lib/screens/address/
    - lib/screens/address/components/
    - lib/screens/sign_up/
    - lib/screens/checkout/
    - lib/screens/checkout/components/
    - lib/screens/products/
    - lib/screens/products/components/
    - lib/screens/who_we_are/
    - lib/screens/who_we_are/components/
    - lib/screens/admin_users/
    - lib/screens/stores_edit/
    - lib/screens/stores_edit/components/
    - lib/screens/admin_orders/
    - lib/screens/product_edit/
    - lib/screens/product_edit/components/
    - lib/screens/products_share/
    - lib/screens/products_share/components/
    - lib/screens/product_details/
    - lib/screens/product_selected/
    - lib/screens/sales_confirmation/
    - lib/screens/policy_and_documents/
    - lib/screens/policy_and_documents/components/
    - lib/services/
    - lib/services/db_api/
    - lib/generated/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
flutter_intl:
  enabled: true
