name: brn_ecommerce
description: Loja Virtual pertencente a empresa - BRN Info_Dev (CNPJ. 52.129.576./001-57)- 
  Desenvolvida pelo Analista e Dev. Bruno Salgado. 
  Contato (82) 9 9984-5889
  Copyright 2024.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.6+01

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.18.1
  collection: ^1.18.0
  cupertino_icons: ^1.0.6
  cloud_firestore: ^4.15.7
  firebase_auth: ^4.17.7
  firebase_storage: ^11.6.8
  firebase_core: ^2.26.0
  firebase_performance: ^0.9.3+16
  firebase_remote_config: ^4.3.16
  firebase_analytics: ^10.8.8
  firebase_crashlytics: ^3.4.17
  provider: ^6.1.2
  fan_carousel_image_slider: ^0.1.2
  carousel_slider: ^4.2.1
  staggered_grid_view_flutter: ^0.0.4
  transparent_image: ^2.0.1
  alphabet_list_scroll_view_fix: ^2.0.2
  flutter_slidable: ^3.0.1
  url_launcher: ^6.2.5
  image_picker: ^1.0.7
  custom_universal_html: ^2.0.0
  image_cropper: ^4.0.1
  path_provider: ^2.1.2
  uuid: ^3.0.7
  dio: ^5.4.1
  brasil_fields: ^1.14.1
  geolocator: ^11.0.0
  sliding_up_panel: ^2.0.0+1
  screenshot: ^2.1.0
  http: ^0.13.3
  gallery_saver: ^2.3.2
  font_awesome_flutter: ^10.7.0
  permission_handler: ^11.3.0
  share_plus: ^7.2.2
  markdown_editable_textinput: ^2.2.0
  flutter_markdown: ^0.6.21
  youtube_player_iframe: ^4.0.4
  flutter_colorpicker: ^1.0.3
  flutter_spinkit: ^5.2.0
  flutter_facebook_auth: ^5.0.11
  google_sign_in: ^6.2.1
  package_info_plus: ^5.0.1
  assets_audio_player: ^3.1.1
  map_launcher: ^3.1.0
  flutter_svg: ^2.0.9
  url_strategy: ^0.2.0
  flip_card: ^0.7.0
  credit_card_type_detector: ^3.0.0
  keyboard_actions: ^4.2.0
  mailer: ^6.1.0
  auto_size_text: ^3.0.0
  google_fonts: ^4.0.4
  decorated_text: ^0.1.0
  #  //TODO: configurar go_router
  #  go_router: ^7.1.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^5.4.4
  lint: ^2.3.0
  analyzer: ^6.4.1
  logger: ^2.1.0
  flutter_lints: ^3.0.1
  #  intl_translation: ^0.18.2
  file: ^7.0.0
  build_web_compilers: ^4.0.9
  build_runner: ^2.4.8
  device_preview: ^1.1.0

# The following section is specific to Flutter packages.
flutter:

  uses-material-design: true

  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  assets:
    - assets/images/
    - assets/logo/
    - assets/docs/
    - assets/vignette/
    - assets/icons/
    - lib/
    - lib/common/
    - lib/common/cards/
    - lib/common/buttons/
    - lib/common/functions/
    - lib/common/drawer/
    - lib/common/drawer/components/
    - lib/models/
    - lib/models/locations_services/
    - lib/helpers/
    - lib/helpers/themes/
    - lib/helpers/themes/factory_colors/
    - lib/views/
    - lib/views/cart/
    - lib/views/cart/components/
    - lib/views/home/
    - lib/views/home/components/
    - lib/views/login/
    - lib/views/orders/
    - lib/views/orders/components/
    - lib/views/stores/
    - lib/views/stores/components/
    - lib/views/address/
    - lib/views/address/components/
    - lib/views/sign_up/
    - lib/views/checkout/
    - lib/views/checkout/components/
    - lib/views/products/
    - lib/views/products/components/
    - lib/views/who_we_are/
    - lib/views/who_we_are/components/
    - lib/views/admin_users/
    - lib/views/stores_edit/
    - lib/views/stores_edit/components/
    - lib/views/admin_orders/
    - lib/views/product_edit/
    - lib/views/product_edit/components/
    - lib/views/products_share/
    - lib/views/products_share/components/
    - lib/views/product_details/
    - lib/views/product_selected/
    - lib/views/sales_confirmation/
    - lib/views/policy_and_documents/
    - lib/views/policy_and_documents/components/
    - lib/services/
    - lib/services/db_api/
    - lib/generated/
    - lib/l10n/
    - lib/views/admin_settings/
    - lib/views/admin_settings/components/
    - lib/views/product_categories/
    - lib/views/product_categories/components/
    - lib/views/product_best_selling/
    - lib/common/messengers/
    - lib/common/messengers/components/
    - lib/common/advertising/
    - lib/common/advertising/components/
    - lib/common/miscellaneous/
    - lib/common/formatted_fields/
    - lib/common/sliding_up_panel/
    - lib/common/sliding_up_panel/components/
    - lib/models/sales/
    - lib/models/users/
    - lib/models/views/
    - lib/models/products/
    - lib/models/products/categories/
    - lib/models/admin_area/
    - lib/models/admin_area/configs/
    - lib/models/users_area/
    - lib/helpers/product_categories_factory_lists/
    - lib/services/config/
    - lib/services/development_monitoring/
    - lib/services/firebase_remote_configs/
    - lib/generated/intl/
    - lib/generated/l10n/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
flutter_intl:
  enabled: false
