name: brn_ecommerce
description: Loja Virtual pertencente a empresa - BRN Info_Dev (CNPJ. 52.129.576./0001-57)-
  Desenvolvida pelo Analista e Dev. Bruno Salgado.
  Contato (82) 9 8178-8227
  Copyright 2024.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.7+00

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  alphabet_scroll_view: ^0.3.2
  audioplayers: ^6.0.0
  auto_size_text: ^3.0.0
  brasil_fields: ^1.14.3
  cloud_firestore: ^6.0.0
  credit_card_type_detector: ^3.0.0
  custom_universal_html: ^2.0.0
  dio: ^5.4.3+1
  firebase_analytics: ^12.0.0
  firebase_auth: ^6.0.0
  firebase_core: ^4.0.0
  firebase_crashlytics: ^5.0.0
  firebase_performance: ^0.11.0
  firebase_remote_config: ^6.0.0
  firebase_storage: ^13.0.0
  file: ^7.0.0
  flip_card: ^0.7.0
  flutter_colorpicker: ^1.1.0
  flutter_facebook_auth: ^7.0.0
  #gpt_markdown: ^1.1.2
  flutter_markdown: ^0.7.1
  flutter_slidable: ^4.0.0
  flutter_spinkit: ^5.2.1
  flutter_svg: ^2.0.10+1
  font_awesome_flutter: ^10.7.0
  geolocator: ^14.0.2
  google_fonts: ^6.2.1
  google_sign_in: ^7.1.1
  http: ^1.2.1
  image_cropper: ^9.1.0
  image_gallery_saver_plus: ^4.0.1
  image_picker: ^1.1.1
  intl: ^0.20.2
  keyboard_actions: ^4.2.0
  mailer: ^6.1.0
  map_launcher: ^4.0.0
  markdown_toolbar: ^0.5.0
  package_info_plus: ^8.0.0
  path_provider: ^2.1.3
  permission_handler: ^12.0.1
  provider: ^6.1.2
  screenshot: ^3.0.0
  share_plus: ^11.0.0
  sliding_up_panel: ^2.0.0+1
  staggered_grid_view_flutter: ^0.0.4
  url_launcher: ^6.2.6
  uuid: ^4.4.0
  youtube_player_iframe: ^5.1.2
  #  //TODO: Possível substituição de dependências
  #url_strategy: ^0.3.0
  transparent_image: ^2.0.1
  decorated_text: ^0.1.0
  carousel_slider: ^5.1.1
  fan_carousel_image_slider: ^1.0.1
  collection: ^1.18.0
  vibration: ^3.1.3
  device_preview: any
  logger: any


dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.10
  build_web_compilers: ^4.0.10
  flutter_lints: ^6.0.0
  lint: ^2.3.0

  # //TODO: implementar dependencias
  #  intl_translation: ^0.18.2
  #  mockito: ^5.4.4

# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/logo/
    - assets/docs/
    - assets/vignette/
    - assets/icons/
    - lib/
    - lib/common/
    - lib/common/cards/
    - lib/common/buttons/
    - lib/common/functions/
    - lib/common/drawer/
    - lib/common/drawer/components/
    - lib/models/
    - lib/models/locations_services/
    - lib/helpers/
    - lib/helpers/themes/
    - lib/helpers/themes/factory_colors/
    - lib/views/
    - lib/views/cart/
    - lib/views/cart/components/
    - lib/views/home/
    - lib/views/home/components/
    - lib/views/login/
    - lib/views/orders/
    - lib/views/orders/components/
    - lib/views/stores/
    - lib/views/stores/components/
    - lib/views/address/
    - lib/views/address/components/
    - lib/views/sign_up/
    - lib/views/checkout/
    - lib/views/checkout/components/
    - lib/views/products/
    - lib/views/products/components/
    - lib/views/who_we_are/
    - lib/views/who_we_are/components/
    - lib/views/admin_users/
    - lib/views/stores_edit/
    - lib/views/stores_edit/components/
    - lib/views/admin_orders/
    - lib/views/product_edit/
    - lib/views/product_edit/components/
    - lib/views/products_share/
    - lib/views/products_share/components/
    - lib/views/product_details/
    - lib/views/product_selected/
    - lib/views/sales_confirmation/
    - lib/views/policy_and_documents/
    - lib/views/policy_and_documents/components/
    - lib/services/
    - lib/services/db_api/
    - lib/generated/
    - lib/l10n/
    - lib/views/admin_settings/
    - lib/views/admin_settings/components/
    - lib/views/product_categories/
    - lib/views/product_categories/components/
    - lib/common/messengers/
    - lib/common/messengers/components/
    - lib/common/advertising/
    - lib/common/advertising/components/
    - lib/common/miscellaneous/
    - lib/common/formatted_fields/
    - lib/common/sliding_up_panel/
    - lib/common/sliding_up_panel/components/
    - lib/models/sales/
    - lib/models/users/
    - lib/models/views/
    - lib/models/products/
    - lib/models/products/categories/
    - lib/models/admin_area/
    - lib/models/admin_area/configs/
    - lib/models/users_area/
    - lib/helpers/product_categories_factory_lists/
    - lib/services/config/
    - lib/services/development_monitoring/
    - lib/services/firebase_remote_configs/
    - lib/generated/intl/
    - lib/generated/l10n/
    - web/flutter_bootstrap.js

flutter_intl:
  enabled: false
