name: brn_ecommerce
description: Loja Virtual BRN Info_Dev
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.2+44

environment:
  sdk: '>=3.0.3 <4.0.0'

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter
  intl: ^0.18.1
  collection: ^1.17.1
  cupertino_icons: ^1.0.5
  cloud_firestore: ^4.8.5
  firebase_auth: ^4.7.3
  firebase_storage: ^11.2.6
  firebase_core: ^2.15.1
  provider: ^6.0.5
  fan_carousel_image_slider: ^0.1.2
  carousel_slider: ^4.2.1
  staggered_grid_view_flutter: ^0.0.4
  transparent_image: ^2.0.1
  alphabet_list_scroll_view_fix: ^2.0.2
  flutter_slidable: ^3.0.0
  url_launcher: ^6.1.12
  image_picker: ^1.0.2
  custom_universal_html: ^2.0.0
  image_cropper: ^4.0.1
  path_provider: ^2.1.0
  uuid: ^3.0.7
  dio: ^5.3.2
  brasil_fields: ^1.14.0
  geolocator: ^10.0.0
  sliding_up_panel: ^2.0.0+1
  screenshot: ^2.1.0
  http: ^0.13.3
  gallery_saver: ^2.3.2
  font_awesome_flutter: ^10.5.0
  permission_handler: ^10.4.3
  share_plus: ^7.1.0
  markdown_editable_textinput: ^2.2.0
  flutter_markdown: ^0.6.17+1
  youtube_player_iframe: ^4.0.4
  flutter_colorpicker: ^1.0.3
  flutter_spinkit: ^5.2.0
  flutter_facebook_auth: ^5.0.11
  google_sign_in: ^6.1.4
  package_info_plus: ^4.1.0
  assets_audio_player: ^3.1.0
  map_launcher: ^2.5.0+1
  flutter_svg: ^2.0.7
  url_strategy: ^0.2.0
  flip_card: ^0.7.0
  credit_card_type_detector: ^3.0.0
  keyboard_actions: ^4.2.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  lint: ^2.1.2
  analyzer: ^6.2.0
  logger: ^2.0.1
  firebase_performance: ^0.9.2+5

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^2.0.2

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  assets:
    - assets/images/
    - assets/logo/
    - assets/docs/
    - assets/vignette/
    - assets/icons/
    - lib/
    - lib/common/
    - lib/common/cards/
    - lib/common/button/
    - lib/common/functions/
    - lib/common/custom_drawer/
    - lib/common/custom_drawer/components/
    - lib/common/formated_fields/
    - lib/models/
    - lib/models/chearch_cep/
    - lib/helpers/
    - lib/helpers/themes/
    - lib/helpers/themes/factory_colors/
    - lib/screens/
    - lib/screens/base/
    - lib/screens/cart/
    - lib/screens/cart/components/
    - lib/screens/home/
    - lib/screens/home/components/
    - lib/screens/login/
    - lib/screens/orders/
    - lib/screens/orders/components/
    - lib/screens/stores/
    - lib/screens/stores/components/
    - lib/screens/address/
    - lib/screens/address/components/
    - lib/screens/sign_up/
    - lib/screens/checkout/
    - lib/screens/checkout/components/
    - lib/screens/products/
    - lib/screens/products/components/
    - lib/screens/who_we_are/
    - lib/screens/who_we_are/components/
    - lib/screens/admin_users/
    - lib/screens/stores_edit/
    - lib/screens/stores_edit/components/
    - lib/screens/admin_orders/
    - lib/screens/product_edit/
    - lib/screens/product_edit/components/
    - lib/screens/products_share/
    - lib/screens/products_share/components/
    - lib/screens/product_details/
    - lib/screens/product_selected/
    - lib/screens/sales_confirmation/
    - lib/screens/policy_and_documents/
    - lib/screens/policy_and_documents/components/
    - lib/services/
    - lib/services/db_api/
    - lib/generated/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
